name: 'Custom S3 cache'
description: 'Save and restore cache artifacts from AWS s3 bucket'
author: Alina Freydina

inputs:
  cache_action:
    description: "An action to do with cache: save or restore"
    required: true
  cache_path:
    description: Absolute or relative path where cache will be restored to or saved from
    required: true
    default: .
  s3_bucket_name:
    description: AWS S3 bucket name to save cache to or restore cache from
    required: true
  cache_key:
    description: A cache key wich used only to save cache to s3 bucket
    required: false
  restore_keys:
    description: 'An ordered list of keys to use for restoring cache from s3 bucket'
    required: false

runs:
  using: "composite"
  steps:
  - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash
  - run: ./cache.sh
    shell: bash

